rateio:
  intervalo: 2

excel:
  abaGop: 6
  extensao: xlsm
  inicioDocumento: 4

cooperativas:
  nomes:
    - "Sicredi Pioneira RS"
    - "Sicredi Planalto RS MG"
    - "Sicredi Raizes RS SC MG"
    - "Sicredi Serrana RS ES"
    - "Sicredi Uniao Metropolitana RS"
    - "Sicredi Vale do Jaguari e Zona da Mata RS MG"
    - "Sicredi Vale do Rio Pardo RS"
    - "Sicredi Uniestados"
    - "Sicredi Sul Minas RS MG"


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
